#!/usr/bin/env bash
# this script configures localhost and facebook.com IP addresses in /etc/hosts

# check if running as the root
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

# backup the current /etc/hosts file
cp /etc/hosts /etc/hosts.bak

# modify the /etc/hosts file
sed -i '/127.0.0.1/s/127.0.0.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
